---
services:
  dimos-unitree-agents:
    image: dimos-unitree-agents:latest
    build: 
      context: ../../../
      dockerfile: docker/unitree/agents/Dockerfile
    env_file:
      - ../../../.env
    environment:
      PYTHONUNBUFFERED: 1
      ROBOT_IP: ${ROBOT_IP} 
      CONN_TYPE: ${CONN_TYPE:-webrtc}
      WEBRTC_SERVER_HOST: 0.0.0.0  # Listen on all interfaces
      WEBRTC_SERVER_PORT: ${WEBRTC_SERVER_PORT:-9991}
      DISPLAY: ${DISPLAY:-}  # For GUI applications like rviz2
      ROS_OUTPUT_DIR: /app/assets/output/ros  # Change output directory
      # DIMOS_MAX_WORKERS: ${DIMOS_MAX_WORKERS}
      # TODO: ipc: host
    volumes:
      - ../../../assets:/app/assets
    ports:
      - "5555:5555"
    mem_limit: 8048m
    stdin_open: true
    tty: true

