---
services:
  unitree_ros_dimos:
    image: unitree_ros_dimos:latest
    build:
      context: ../../../
      dockerfile: docker/unitree/ros_dimos/Dockerfile
    env_file:
      - ../../../.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 forwarding
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - ../../../assets/output/:/app/assets/output
    network_mode: "host"  # Required for ROS2 discovery and robot communication
    privileged: true  # Required for hardware access
    devices:
      - /dev/input:/dev/input  # For joystick access
    restart: unless-stopped 
