---
services:
  dimos-unitree-agents-interface:
    image: dimos-unitree-agents-interface:latest
    build: 
      context: ../../../
      dockerfile: docker/unitree/agents_interface/Dockerfile
    env_file:
      - ../../../.env
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_OUTPUT_DIR=/app/assets/output/ros  # Change output directory
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY
      # DIMOS_MAX_WORKERS: ${DIMOS_MAX_WORKERS}
      # TODO: ipc: host
    volumes:
      - ../../../assets:/app/assets
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:ro
      # Persist model caches in host filesystem
      - ../../../assets/model-cache/torch-hub:/root/.cache/torch/hub
      - ../../../assets/model-cache/iopath-cache:/root/.torch/iopath_cache
      - ../../../assets/model-cache/ultralytics:/root/.config/Ultralytics
    network_mode: "host"
    ports:
      - "5555:5555"
    mem_limit: 8048m
    runtime: nvidia
    stdin_open: true
    tty: true
  
  dimos-web-interface:
    build:
      context: ../../../
      dockerfile: docker/interface/Dockerfile
    image: dimos-web-interface:latest
    container_name: dimos-web-interface
    network_mode: "host"
    volumes:
      - ../../../dimos/web/dimos_interface:/app
    depends_on:
      - dimos-unitree-agents-interface